### ISSUE TITLE
InternalTransactionData model error with DataCollectionMode.FULL

### ISSUE THREAD

**Issue by dvdblk** [uzh-eth-mp/app#71]
```
bdcd-data_consumer_eth-1  | 2023-05-12 13:17:19.107 app.consumer ERROR    Caught exception during handling of 0xe5eb010a3bebeded47bcbef040f108bd3cb2c62277f2b1c90bee364a4fc3a93e
bdcd-data_consumer_eth-1  | Traceback (most recent call last):
bdcd-data_consumer_eth-1  |   File "/app/app/consumer.py", line 338, in start_consuming_data
bdcd-data_consumer_eth-1  |     await self.kafka_manager.start_consuming(
bdcd-data_consumer_eth-1  |   File "/app/app/kafka/manager.py", line 344, in start_consuming
bdcd-data_consumer_eth-1  |     await asyncio.gather(timeout_task, consume_task)
bdcd-data_consumer_eth-1  |   File "/app/app/kafka/manager.py", line 318, in _start_listening_on_topic
bdcd-data_consumer_eth-1  |     await on_event_callback(event)
bdcd-data_consumer_eth-1  |   File "/app/app/consumer.py", line 321, in _on_kafka_event
bdcd-data_consumer_eth-1  |     await self._consume_full(tx_data, tx_receipt_data, w3_tx_data, w3_tx_receipt)
bdcd-data_consumer_eth-1  |   File "/app/app/consumer.py", line 297, in _consume_full
bdcd-data_consumer_eth-1  |     await self._handle_transaction(tx_data=tx_data, tx_receipt_data=tx_receipt_data)
bdcd-data_consumer_eth-1  |   File "/app/app/consumer.py", line 152, in _handle_transaction
bdcd-data_consumer_eth-1  |     internal_tx_data = await self.node_connector.get_internal_transactions(
bdcd-data_consumer_eth-1  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bdcd-data_consumer_eth-1  |   File "/app/app/web3/node_connector.py", line 120, in get_internal_transactions
bdcd-data_consumer_eth-1  |     internal_tx_data = list(
bdcd-data_consumer_eth-1  |                        ^^^^^
bdcd-data_consumer_eth-1  |   File "/app/app/web3/node_connector.py", line 121, in <lambda>
bdcd-data_consumer_eth-1  |     map(lambda data: InternalTransactionData(**data), data_dict)
bdcd-data_consumer_eth-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bdcd-data_consumer_eth-1  |   File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
bdcd-data_consumer_eth-1  | pydantic.error_wrappers.ValidationError: 3 validation errors for InternalTransactionData
bdcd-data_consumer_eth-1  | to
bdcd-data_consumer_eth-1  |   field required (type=value_error.missing)
bdcd-data_consumer_eth-1  | input
bdcd-data_consumer_eth-1  |   field required (type=value_error.missing)
bdcd-data_consumer_eth-1  | callType
bdcd-data_consumer_eth-1  |   field required (type=value_error.missing)
```

**Comment by dvdblk** [comment]
Reproducible in 96e22656ab75af4fb10951b1e05ce75e527aab07

**Comment by dvdblk** [comment]
Think we should just remove all the `NOT NULL` constraints in every single table, it doesn't matter if some of them are null anyway @cinan93

**Comment by dvdblk** [comment]
partial mode, uniswap contract
```
bdcd-data_consumer_eth-13  | 2023-05-15 04:44:26.767 app.consumer ERROR    Caught exception during handling of 0x180c1c1ad06d7b589da71bca0fdf7048bef378fd42d3fd435da852cccc0693c3
bdcd-data_consumer_eth-13  | Traceback (most recent call last):
bdcd-data_consumer_eth-13  |   File "/app/app/consumer.py", line 342, in start_consuming_data
bdcd-data_consumer_eth-13  |     await self.kafka_manager.start_consuming(
bdcd-data_consumer_eth-13  |   File "/app/app/kafka/manager.py", line 365, in start_consuming
bdcd-data_consumer_eth-13  |     await asyncio.gather(timeout_task, consume_task)
bdcd-data_consumer_eth-13  |   File "/app/app/kafka/manager.py", line 333, in _start_listening_on_topic_task
bdcd-data_consumer_eth-13  |     await on_event_callback(event)
bdcd-data_consumer_eth-13  |   File "/app/app/consumer.py", line 327, in _on_kafka_event
bdcd-data_consumer_eth-13  |     await self._consume_partial(tx_data, tx_receipt_data, w3_tx_data, w3_tx_receipt)
bdcd-data_consumer_eth-13  |   File "/app/app/consumer.py", line 280, in _consume_partial
bdcd-data_consumer_eth-13  |     await self._handle_transaction(tx_data=tx_data, tx_receipt_data=tx_receipt_data)
bdcd-data_consumer_eth-13  |   File "/app/app/consumer.py", line 153, in _handle_transaction
bdcd-data_consumer_eth-13  |     internal_tx_data = await self.node_connector.get_internal_transactions(
bdcd-data_consumer_eth-13  |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bdcd-data_consumer_eth-13  |   File "/app/app/web3/node_connector.py", line 173, in get_internal_transactions
bdcd-data_consumer_eth-13  |     internal_tx_data = list(
bdcd-data_consumer_eth-13  |                        ^^^^^
bdcd-data_consumer_eth-13  |   File "/app/app/web3/node_connector.py", line 174, in <lambda>
bdcd-data_consumer_eth-13  |     map(lambda data: InternalTransactionData(**data), data_dict)
bdcd-data_consumer_eth-13  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bdcd-data_consumer_eth-13  |   File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
bdcd-data_consumer_eth-13  | pydantic.error_wrappers.ValidationError: 3 validation errors for InternalTransactionData
bdcd-data_consumer_eth-13  | to
bdcd-data_consumer_eth-13  |   field required (type=value_error.missing)
bdcd-data_consumer_eth-13  | input
bdcd-data_consumer_eth-13  |   field required (type=value_error.missing)
bdcd-data_consumer_eth-13  | callType
bdcd-data_consumer_eth-13  |   field required (type=value_error.missing)
```

**Comment by dvdblk** [comment]
Still persists, the pydantic classes need to be updated to have optional fields for `to`, `input` and `callType`
