### ISSUE TITLE
Remove limits on length in DB

### ISSUE THREAD

**Issue by dvdblk** [uzh-eth-mp/app#72]
Length limits (even for `bytea`) should be removed imo:

```
bdcd-data_consumer_eth-2  | 2023-05-12 13:17:34.411 app.consumer ERROR    Caught exception during handling of 0x5a0d1174b2f0626769fe90c04ba160a6fe1ca1b82f55dc05ebadf4fb824b3c69
bdcd-data_consumer_eth-2  | Traceback (most recent call last):
bdcd-data_consumer_eth-2  |   File "/app/app/consumer.py", line 338, in start_consuming_data
bdcd-data_consumer_eth-2  |     await self.kafka_manager.start_consuming(
bdcd-data_consumer_eth-2  |   File "/app/app/kafka/manager.py", line 344, in start_consuming
bdcd-data_consumer_eth-2  |     await asyncio.gather(timeout_task, consume_task)
bdcd-data_consumer_eth-2  |   File "/app/app/kafka/manager.py", line 318, in _start_listening_on_topic
bdcd-data_consumer_eth-2  |     await on_event_callback(event)
bdcd-data_consumer_eth-2  |   File "/app/app/consumer.py", line 321, in _on_kafka_event
bdcd-data_consumer_eth-2  |     await self._consume_full(tx_data, tx_receipt_data, w3_tx_data, w3_tx_receipt)
bdcd-data_consumer_eth-2  |   File "/app/app/consumer.py", line 297, in _consume_full
bdcd-data_consumer_eth-2  |     await self._handle_transaction(tx_data=tx_data, tx_receipt_data=tx_receipt_data)
bdcd-data_consumer_eth-2  |   File "/app/app/consumer.py", line 144, in _handle_transaction
bdcd-data_consumer_eth-2  |     await self.db_manager.insert_transaction(
bdcd-data_consumer_eth-2  |   File "/app/app/db/manager.py", line 100, in insert_transaction
bdcd-data_consumer_eth-2  |     await self.db.execute(
bdcd-data_consumer_eth-2  |   File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 320, in execute
bdcd-data_consumer_eth-2  |     _, status, _ = await self._execute(
bdcd-data_consumer_eth-2  |                    ^^^^^^^^^^^^^^^^^^^^
bdcd-data_consumer_eth-2  |   File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1659, in _execute
bdcd-data_consumer_eth-2  |     result, _ = await self.__execute(
bdcd-data_consumer_eth-2  |                 ^^^^^^^^^^^^^^^^^^^^^
bdcd-data_consumer_eth-2  |   File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1684, in __execute
bdcd-data_consumer_eth-2  |     return await self._do_execute(
bdcd-data_consumer_eth-2  |            ^^^^^^^^^^^^^^^^^^^^^^^
bdcd-data_consumer_eth-2  |   File "/usr/local/lib/python3.11/site-packages/asyncpg/connection.py", line 1731, in _do_execute
bdcd-data_consumer_eth-2  |     result = await executor(stmt, None)
bdcd-data_consumer_eth-2  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^
bdcd-data_consumer_eth-2  |   File "asyncpg/protocol/protocol.pyx", line 201, in bind_execute
bdcd-data_consumer_eth-2  | asyncpg.exceptions.StringDataRightTruncationError: value too long for type character varying(65536)```

**Comment by dvdblk** [comment]
Reproducible in 96e22656ab75af4fb10951b1e05ce75e527aab07
